defaults: &defaults
  adapter: mysql
  encoding: utf8
  username: dev
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock

development:
  database: wiki_development
  <<: *defaults

test:
  database: wiki_test
  <<: *defaults

production:
  database: wiki_production
  <<: *defaults
